### ISSUE TITLE
Appendix Chapters

### ISSUE THREAD

**Issue by vbollen** [seanmossman/WSU_ThesisTemplate_LaTeX#1]
Appendices should be \chapters instead of \section. In the table of contents (TOC) all the entries are shifted over to the section indentation. Should they not line up with the chapters?

Looking at other dissertations from my group it looks like they have appendices as chapters labeled A, B, etc, and then section that either have just numbers or numerals, e.g. A.I, A.II or A.1, A.2.

**Comment by seanmossman** [comment]
This setup was a compromise due to a conflict with the table of contents. If the chapter labels are changed to "Appendix A", "Appendix B", etc. then they overlap with the text indicating the appendix title in the table of context. A true fix on this would require a realignment of the label and title spacing in the table of contents which seemed like more trouble than it was worth. Alternate ideas are welcome.

The current form has one Appendix as a chapter and each individual appendix is actually a section of the full appendix. 

Changing to \chapter headers in the appendix works ok. One bug I have remaining is that the Appendix header ends up on its own page because each chapter necessarily starts on a new page. Also the Appendix headers say "Chapter A. Appendix Name". Working on how to reset the chapter headers.

**Comment by seanmossman** [comment]
Ok, I have a fix for the Appendix using chapter headers. I'll run it by Daniel at the graduate school regarding  the APPENDIX title. That is, should the word "APPENDIX" appear on its own page (with or without a page number) before beginning the appendix chapters.

**Comment by vbollen** [comment]
Sounds good. 
Side note: I also made a development branch that we should work in when trying out new things like this. The master branch should always be graduate school approved

**Comment by vbollen** [comment]
Just using \section messes up the equation counter as well.

**Comment by seanmossman** [comment]
The graduate school has indicated that either method of organizing an appendix is acceptable. Dual versions will be created to reflect this choice.
