### ISSUE TITLE
Little bugs

### ISSUE THREAD

**Issue by seanmossman** [seanmossman/WSU_ThesisTemplate_LaTeX#3]
Here we can collect little bugs that are quick and easy to fix. For example, on the signature page I think there is an over-sized line break in the body text that was missed by the graduate school. This is easily fixed in the style file WSU_thesis.sty by streamlining the text portion of the signature page.

**Comment by vbollen** [comment]
I think it'd be better to have an issue for each bug that can't be fixed immediately, no matter how small. We also don't have to make a new issue for every bug we find, especially if they're easy fixes, which should just be fixed on the spot an committed.

My fear of having one big thread for little bugs is that it could become hard to see what see what still needs to be done with each bug.

We could instead also add a project that has a todo list of smaller bugs.

**Comment by seanmossman** [comment]
Sure, I already fixed this bug. I'm not sure how to manage little bugs as they crop up and having lots of minor commits to the master branch seems sub-optimal as well.

**Comment by vbollen** [comment]
Smaller commits are actually preferable a lot of times since it’s easier to track back what has been changed. If there’s always one big patch that just says “bug fixes”, it’s not clear what got changed. If there are a lot of smaller commits, for example “fixed extra line break in signature page”, it’s a lot clearer.

**Comment by vbollen** [comment]
Should we close this issue then if you've fixed that bug?
